// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFarmacias.Infrastructure.Persistence;

#nullable disable

namespace SistemaFarmacias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmaciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalGasto")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UltimaCompraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimaInteracaoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FarmaciaId", "Telefone")
                        .IsUnique();

                    b.ToTable("contatos", (string)null);
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Farmacia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("farmacias", (string)null);
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Interacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmaciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntencaoDetectada")
                        .HasColumnType("text");

                    b.Property<string>("MensagemEnviada")
                        .HasColumnType("text");

                    b.Property<string>("MensagemRecebida")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.HasIndex("FarmaciaId");

                    b.ToTable("interacoes", (string)null);
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.ReativacaoEnviada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContatoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmaciaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.HasIndex("FarmaciaId");

                    b.ToTable("reativacoes_enviadas", (string)null);
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.WhatsappConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<Guid>("FarmaciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("HorarioFuncionamento")
                        .HasColumnType("text");

                    b.Property<string>("MensagemSaudacao")
                        .HasColumnType("text");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsappNumberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FarmaciaId");

                    b.HasIndex("WhatsappNumberId")
                        .IsUnique();

                    b.ToTable("whatsapp_config", (string)null);
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Contato", b =>
                {
                    b.HasOne("SistemaFarmacias.Domain.Entities.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmacia");
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Interacao", b =>
                {
                    b.HasOne("SistemaFarmacias.Domain.Entities.Contato", "Contato")
                        .WithMany("Interacoes")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFarmacias.Domain.Entities.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Farmacia");
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.ReativacaoEnviada", b =>
                {
                    b.HasOne("SistemaFarmacias.Domain.Entities.Contato", "Contato")
                        .WithMany("Reativacoes")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFarmacias.Domain.Entities.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Farmacia");
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.WhatsappConfig", b =>
                {
                    b.HasOne("SistemaFarmacias.Domain.Entities.Farmacia", "Farmacia")
                        .WithMany()
                        .HasForeignKey("FarmaciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmacia");
                });

            modelBuilder.Entity("SistemaFarmacias.Domain.Entities.Contato", b =>
                {
                    b.Navigation("Interacoes");

                    b.Navigation("Reativacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
